### ISSUE TITLE
Daemon not started after running install-vpl-sh

### ISSUE THREAD

**Issue by fabiosl** [jcrodriguez-dis/vpl-jail-system#1]
Hi @jcrodriguez-dis,

I have successfully installed the plugin. However, I'm having an issue when I try to install the Jail server. 

I'm following the instructions provided on this page:
http://vpl.dis.ulpgc.es/index.php/en/documentation/75-how-to-install-vpl-jail-system

This is what happens when I try to install the jail server: https://gist.github.com/fabiosl/363a854a0cc4ca249934 
On the bottom of the page you can notice a "Daemon not started"...

Instruction number 6 says that I should  

```
6. Edit the file /etc/vpl/vpl-jail-system.conf. Set the URLPATH that will be used as key in connections with your execution server
```

The only variable that I need to set is URLPATH, right? That's how my /etc/vpl/vpl-jail-system.conf now: https://gist.github.com/fabiosl/eab17291d0f9838125eb#file-gistfile1-txt

When I try to force the initialization of the server I get the same error:

```
root@ip-10-253-70-8:/home/ubuntu/jail/vpl_jail_system-2.0# sudo service vpl-jail-system start
 * Daemon not started
```

Am I missing something? Any ideas? 

I'm running this version of Ubuntu: 

```
root@ip-10-253-70-8:/home/ubuntu/jail/vpl_jail_system-2.0# uname -a
Linux ip-10-253-70-8 3.11.0-19-generic #33-Ubuntu SMP Tue Mar 11 18:48:32 UTC 2014 i686 i686 i686 GNU/Linux
```

**Comment by iMinion** [comment]
Hello @jcrodriguez-dis ,

I'm also experiencing the similar problem! I've even ran the  command "sudo service vpl-jail-system start -d 8".
Right now I'm using 2.1.1 Jail Server on a Ubuntu based Virtual Machine.

Here's what I get in the logs
> Jun  3 11:37:28 jailserver vpl-jail-system[8253]: Set log mask up to 8
> Jun  3 11:37:28 jailserver vpl-jail-system[8253]: correctFile 1 'jail' 0:0
> Jun  3 11:37:28 jailserver vpl-jail-system[8253]: correctFile 1 'var' 0:0
> Jun  3 11:37:28 jailserver vpl-jail-system[8253]: correctFile 1 'vpl-jail-system' 0:0
> Jun  3 11:37:28 jailserver vpl-jail-system[8253]: SSL_CTX_use_certificate_chain_file() fail: error:02001002:system library:fopen:No such file or directory

Thanks,
Sri Ram Manoj K
