### ISSUE TITLE
Drop Python2 support

### ISSUE THREAD

**Issue by jeroenhabets** [jcrodriguez-dis/vpl-jail-system#68]
Not sure if in 2023 this classifies as a Bug [1] or a Feature request but shouldn't Python2 be dropped, _especially_ from the main dev tools install (if still needed by some or for not breaking things it could be moved to the auxiliary tools):

```
Installing Python2 interpreter: python2 [OK]
Installing Python2 pydb: [Package not found. Checked pydb]
Installing Python2 pudb: [Package not found. Checked python-pudb]
Installing Python2 Tk: python-tk [OK]
Installing Python2 NumPy: [Package not found. Checked python-numpy]
Installing Python2 pandas: [Package not found. Checked python-pandas]
Installing Python2 Matplotlib: [Package not found. Checked python-matplotlib]
```

[1] https://www.softwaretestinghelp.com/python-2-end-of-life-eol/#Security_Risks_For_Using_Python_2_Past_EOL

**Comment by jcrodriguez-dis** [comment]
Certainly. Given that Python 2 reached its End of Life (EOL) on January 1, 2020, its inclusion in the VPL installer raises legitimate concerns about security and maintainability. Therefore, Python 2 will be removed from the VPL installer in the upcoming release. For users who still require Python 2 for legacy projects, it will remain available in VPL but they must install it at their own risk.

**Comment by jeroenhabets** [comment]
Thanks @jcrodriguez-dis 🥇!
(this has been in place since 4.0 AFAICT)
