### ISSUE TITLE
Support for Rust

### ISSUE THREAD

**Issue by piosystems** [jcrodriguez-dis/vpl-jail-system#69]
Include support for Rust programming language, out-of-th-box

**Comment by jeroenhabets** [comment]
@jcrodriguez-dis it seems you delivered Rust support with [VPL Jail System 4.0.0 Release](https://github.com/jcrodriguez-dis/vpl-jail-system/releases/tag/V4.0.0) 🥇 so this can be marked completed by you or @piosystems...
