### ISSUE TITLE
Error using java-GUI "no X11 DISPLAY set"

### ISSUE THREAD

**Issue by OZimmermann** [jcrodriguez-dis/vpl-jail-system#76]
Hi, thank you very much for the great work. The installation under Ubuntu 64-bit went smoothly. The plugin in Moodle also works with Java program. 
However, when I try to start a program with a graphical user interface, I get the following error: 

> java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found ...

What can I do?
Best regards 
Oliver

**Comment by OZimmermann** [comment]
Hi Juan Carlos,
thanks for your quick reply. I am now using VPL regularly via Moodle and my students like VPL :-)

I am using a collection of classes imported as a jar, which I have attached for reference. It's mainly the „viualisiere()" method in the "Graph_gewichtet" class in the "graphen" project.
The following libraries are used
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.awt.*;
import java.awt.event.*;

I attached a screencast and the downloaded zip of VPL.

Kind regards
Oliver

https://github.com/jcrodriguez-dis/vpl-jail-system/assets/82403411/25df04a2-c9fb-4e77-8647-7d7d36334753


[VPL-Prim.zip](https://github.com/jcrodriguez-dis/vpl-jail-system/files/15041536/VPL-Prim.zip)

**Comment by jeroenhabets** [comment]
In case you haven't gotten this to work: @OZimmermann looking at your code in your video you'd just need to import one of the files mentioned by @jcrodriguez-dis, e.g. `import javax.swing.JFrame;`

AFAICT the VPL code is _not_ able to check indirect imports (e.g. via your `graphen.*` packages in your .jar). So you need an import in your source file itself. (At least until the future "manual selection options for GUI mode" would be developed and released)

**Comment by OZimmermann** [comment]
Hello to all, everything's great now.
Thanks
Oliver
Am 17. Sept. 2024, 23:13 +0200 schrieb Jeroen Habets ***@***.***>:

**Comment by jeroenhabets** [comment]
Thank you for reporting back your success @OZimmermann ! Could you please close this issue then?

**Comment by OZimmermann** [comment]
Sure, thanks for help and great work.
I showed many schools your great tool :-)
By, Oliver
Am 15. Dez. 2024, 19:49 +0100 schrieb Jeroen Habets ***@***.***>:
